# ghost-tooth-ui - a PS5 companion payload that gives ghost-toothAPI a
# manual headset picker on the Media tab.
#
#   make host      -> build/ghost-tooth-ui   (development binary for this PC)
#   make preview   -> host build + mock payload, serves the UI on :8899
#   make test      -> host build + unit tests + API smoke test
#   make sdk       -> fetch/install the PS5 toolchain (Linux, needs sudo once)
#   make ps5       -> build/ghost-tooth-ui.elf (the PS5 payload, needs the SDK)
#   make deploy    -> push that ELF to a running payload loader (elfldr/websrv)
#   make icon      -> regenerate assets/icon0.png
#
# Copyright (C) 2026 Ghost-tooth-ui contributors
# SPDX-License-Identifier: GPL-3.0-or-later

VERSION    := 0.1.0
TITLE_ID   := GTTH00001
EMBED_PAYLOAD ?= 1
PAYLOAD_SRC := ghost-toothAPI.elf
PYTHON     ?= python3

SRC        := src
BUILD      := build
BIN        := $(BUILD)/ghost-tooth-ui
PS5_BIN    := $(BUILD)/ghost-tooth-ui.elf

SRCS := $(SRC)/main.c $(SRC)/gt_util.c $(SRC)/gt_json.c $(SRC)/gt_log.c \
        $(SRC)/gt_link.c $(SRC)/gt_httpd.c $(SRC)/gt_assets.c \
        $(SRC)/gt_tile.c $(SRC)/gt_proc.c $(SRC)/gt_notify.c
HEADERS := $(SRC)/gt.h $(SRC)/gt_incbin.h
ASSETS := assets/index.html assets/main.css assets/main.js assets/icon0.png

WARN := -Wall -Wextra -Werror -Wno-unused-parameter
BASE_CFLAGS := -std=gnu11 $(WARN) -D_GNU_SOURCE -Isrc \
               -DGT_VERSION=\"$(VERSION)\"

# ----------------------------------------------------------------- host build
HOST_CC     ?= cc
HOST_CFLAGS := $(BASE_CFLAGS) -O1 -g -DGTT_HOST=1 -DGT_HOST_SIM=1 \
               -DGTT_ROOT_DEFAULT=\"$(CURDIR)/$(BUILD)/console-root\"
HOST_LDFLAGS := -pthread

# ------------------------------------------------------------------ PS5 build
# prospero.mk is what pulls in the clang toolchain; a plain SDK checkout has the
# headers but no generated toolchain file, and that is enough for "make
# check-ps5" below - so include it only when it exists, and never fail at parse
# time (a missing SDK must not break "make host" or "make test").
ifdef PS5_PAYLOAD_SDK
  ifneq ($(wildcard $(PS5_PAYLOAD_SDK)/toolchain/prospero.mk),)
    include $(PS5_PAYLOAD_SDK)/toolchain/prospero.mk
    CC    := $(PS5_PAYLOAD_SDK)/bin/prospero-clang
    STRIP := $(PS5_PAYLOAD_SDK)/bin/prospero-strip
  endif
endif
CC    ?= cc
STRIP ?= true

# TITLE_ID is passed through because the tile id also names the staging
# directory; the tile *name* is deliberately not a -D (make splits flags on
# whitespace, so "Ghost Tooth" would arrive as two arguments) - set it with
# --tile-name= at runtime, or -DTILE_NAME='\"..\"' by hand.
PS5_CFLAGS := $(BASE_CFLAGS) -Oz -DGTT_PS5=1 -DGT_PS5=1 \
              -DTITLE_ID=\"$(TITLE_ID)\" \
              -ffunction-sections -fdata-sections -fno-asynchronous-unwind-tables \
              -fno-unwind-tables
PS5_LDFLAGS := -Wl,--gc-sections
PS5_LDADD   := -lSceAppInstUtil -lSceUserService -lSceSystemService -lSceNotification \
               -lSceIpmi

ifeq ($(EMBED_PAYLOAD),1)
  PS5_CFLAGS += -DGT_EMBED_PAYLOAD=1
  # A prerequisite only when it exists, so that a missing payload is reported by
  # the recipe (with advice) instead of by make's "no rule to make target".
  PAYLOAD_IMG := $(if $(wildcard $(PAYLOAD_SRC)),$(PAYLOAD_SRC))
else
  PAYLOAD_IMG :=
endif

.PHONY: all host ps5 preview test test-unit test-api test-ui check-ps5 \
        dist sdk deploy icon clean distclean

all: ps5

ps5: $(PS5_BIN)

$(BUILD):
	@mkdir -p $(BUILD)

# ---------------------------------------------------------------- toolchain
# The one-time setup for building the console ELF on your own machine. This is
# the packaged toolchain the other ps5-payload-dev projects use: it contains
# prospero-clang, lld, the toolchain/*.mk fragments and the -lSce* stubs, which
# a bare `git clone` of ps5-payload-dev/sdk does not (those are generated by its
# `make install`). Extract it as root, or point PS5_PAYLOAD_SDK at wherever you
# unpacked it:
#
#   sudo tar xf ps5-payload-dev.tar.gz -C /          # -> /opt/ps5-payload-sdk
#   make ps5 PS5_PAYLOAD_SDK=/path/to/ps5-payload-sdk
SDK_URL  ?= https://github.com/ps5-payload-dev/pacbrew-repo/releases/latest/download/ps5-payload-dev.tar.gz
SDK_DEST ?= /

sdk:
	@echo "downloading $(SDK_URL)"
	@curl -fL --retry 3 -o /tmp/ps5-payload-dev.tar.gz "$(SDK_URL)"
	@echo "unpacking into $(SDK_DEST) (needs root)"
	sudo tar xf /tmp/ps5-payload-dev.tar.gz -C $(SDK_DEST)
	@echo
	@echo "done.  build the payload with:"
	@echo "  export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk && make ps5"

# ------------------------------------------------------------- console helper
# PS5_DEPLOY / PS5_HOST / PS5_PORT come from the SDK's toolchain/prospero.sh;
# the defaults below match the SDK samples so this works standalone too.
PS5_HOST   ?= ps5
PS5_PORT   ?= 9021
PS5_DEPLOY ?= $(if $(PS5_PAYLOAD_SDK),$(PS5_PAYLOAD_SDK)/bin/prospero-deploy,prospero-deploy)

deploy: $(PS5_BIN)
	@ if ! command -v "$(PS5_DEPLOY)" >/dev/null 2>&1 && [ ! -x "$(PS5_DEPLOY)" ]; then \
	    echo "no prospero-deploy found; load $(PS5_BIN) with your own loader instead" >&2; \
	    exit 1; \
	  fi
	"$(PS5_DEPLOY)" -h $(PS5_HOST) -p $(PS5_PORT) $(PS5_BIN)

# The ELF as it ships: both variants CI produces, side by side with checksums.
DIST := dist

dist: | $(BUILD)
	@rm -rf $(DIST) && mkdir -p $(DIST)
	$(MAKE) -B ps5 EMBED_PAYLOAD=0
	@cp $(PS5_BIN) $(DIST)/ghost-tooth-ui.elf
	@if [ -f $(PAYLOAD_SRC) ]; then \
	  $(MAKE) -B ps5 EMBED_PAYLOAD=1 && \
	  cp $(PS5_BIN) $(DIST)/ghost-tooth-ui-selfcontained.elf; \
	else \
	  echo "no $(PAYLOAD_SRC) in the repo root - skipping the embedded variant"; \
	fi
	@cd $(DIST) && sha256sum *.elf > ghost-tooth-ui.elf.sha256 && ls -l && cat *.sha256
	@echo "loaded on the console: $(DIST)/ghost-tooth-ui.elf"

# The web assets are linked in through .incbin, so every object must be rebuilt
# when they change; the source tree is small enough for that to be cheap.
# The guard lives in the recipe so that every other target keeps working without
# a toolchain: "make host" and the tests never need PS5_PAYLOAD_SDK at all.
define PS5_GUARD
	@ if [ -z "$(PS5_PAYLOAD_SDK)" ]; then \
	    echo "PS5_PAYLOAD_SDK is undefined - install the toolchain with: make sdk" >&2; \
	    echo "or build the desktop binary with: make host" >&2; exit 1; \
	  fi; \
	  if [ ! -f "$(PS5_PAYLOAD_SDK)/toolchain/prospero.mk" ]; then \
	    echo "$(PS5_PAYLOAD_SDK) has no toolchain/prospero.mk - that is a bare SDK" >&2; \
	    echo "checkout, not an installed one: 'make sdk' installs the packaged toolchain," >&2; \
	    echo "or 'sudo make DESTDIR=/opt/ps5-payload-sdk install' inside the SDK checkout." >&2; \
	    exit 1; \
	  fi; \
	  if [ "$(EMBED_PAYLOAD)" = "1" ] && [ ! -f "$(PAYLOAD_SRC)" ]; then \
	    echo "EMBED_PAYLOAD=1 needs $(PAYLOAD_SRC) in the repo root (it is embedded so the" >&2; \
	    echo "UI can install it itself). Use EMBED_PAYLOAD=0 to build without it." >&2; \
	    exit 1; \
	  fi
endef

$(PS5_BIN): $(SRCS) $(HEADERS) $(ASSETS) $(PAYLOAD_IMG) | $(BUILD)
	$(PS5_GUARD)
	$(CC) $(PS5_CFLAGS) $(PS5_LDFLAGS) -o $@ $(SRCS) $(PS5_LDADD)
	$(STRIP) $@
	@ls -l $@

# Pre-flight for the console build on a machine that has the SDK headers but no
# toolchain: every source must compile with the PS5 defines, including the
# #ifdef'ed AppInst / sysctl / notification paths the host build leaves out.
# One rule per file (rather than a shell loop) so the -D quoting survives.
# The two layouts are probed because a bare SDK checkout keeps its headers in
# include/, while an installed one (the packaged toolchain) keeps them in
# target/include/ next to the sysroot.
PS5_INC := $(firstword $(wildcard $(PS5_PAYLOAD_SDK)/include) \
                        $(wildcard $(PS5_PAYLOAD_SDK)/target/include))
PS5_INC_FREEBSD := $(firstword $(wildcard $(PS5_INC)/freebsd) \
                               $(wildcard $(PS5_PAYLOAD_SDK)/include/freebsd))
PS5_HEADERS := $(if $(PS5_INC),-I$(PS5_INC)) $(if $(PS5_INC_FREEBSD),-I$(PS5_INC_FREEBSD))
SYNTAX      := $(patsubst $(SRC)/%.c,$(BUILD)/%.syntax,$(SRCS))

check-ps5: $(SYNTAX)
	@echo "every source compiles with the PS5 defines"

$(BUILD)/%.syntax: $(SRC)/%.c $(HEADERS) | $(BUILD)
	@ if [ -z "$(PS5_INC)" ]; then \
	    echo "no SDK headers found under PS5_PAYLOAD_SDK=$(PS5_PAYLOAD_SDK) -" >&2; \
	    echo "set PS5_PAYLOAD_SDK to a checkout or an installed toolchain" >&2; exit 1; \
	  fi
	$(HOST_CC) -fsyntax-only $(PS5_CFLAGS) $(PS5_HEADERS) $<
	@touch $@
	@echo "ok   $<"

host: $(BIN)

$(BIN): $(SRCS) $(HEADERS) $(ASSETS) | $(BUILD)
	$(HOST_CC) $(HOST_CFLAGS) -o $@ $(SRCS) $(HOST_LDFLAGS)
	@ls -l $@

# --------------------------------------------------------------- dev / tests
# Desktop preview: the exact UI the console would show, driven by a mock
# ghost-toothAPI (tools/gt-sim.py) that speaks the real log and headset.ini
# formats - so scan, pick and connect can be clicked through without a console
# in the room.
preview: $(BIN)
	@mkdir -p $(BUILD)/console-root
	$(BIN) --demo --port=$${GTT_PREVIEW_PORT:-8899} --root=$(BUILD)/console-root \
	       --sim=$(CURDIR)/tools/gt-sim.py

test: test-unit test-api test-ui

# The UI is three files that have to agree with each other; this catches the
# mismatches (a typo'd element id, a key only in one language) without a browser.
test-ui:
	$(PYTHON) tools/gt-check-ui.py

test-unit: $(BUILD)/test_gt_link
	./$(BUILD)/test_gt_link

$(BUILD)/test_gt_link: tests/test_gt_link.c $(SRC)/gt_util.c $(SRC)/gt_json.c \
                      $(SRC)/gt_log.c $(SRC)/gt_link.c $(SRC)/gt_proc.c \
                      $(SRC)/gt_notify.c $(SRC)/gt_assets.c $(SRC)/gt_tile.c | $(BUILD)
	$(HOST_CC) $(HOST_CFLAGS) -o $@ tests/test_gt_link.c \
	  $(SRC)/gt_util.c $(SRC)/gt_json.c $(SRC)/gt_log.c $(SRC)/gt_link.c \
	  $(SRC)/gt_proc.c $(SRC)/gt_notify.c $(SRC)/gt_assets.c $(SRC)/gt_tile.c \
	  $(HOST_LDFLAGS)

test-api: $(BIN)
	$(PYTHON) tools/gt-smoke.py $(BIN) $(BUILD)/smoke-root $${GTT_PREVIEW_PORT:-8879}

icon:
	$(PYTHON) tools/gt-icon.py assets/icon0.png
	$(PYTHON) tools/gt-check-icon.py assets/icon0.png

clean:
	rm -f $(BUILD)/*.o $(BIN) $(PS5_BIN) $(BUILD)/test_gt_link
	rm -rf $(BUILD)/smoke-root $(BUILD)/console-root

distclean: clean
	rm -rf $(BUILD)
